version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    networks:
      - ecommerce-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

  admin:
    build: ./admin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
